CREATE TABLE "registrations" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"whatsapp" varchar(50) NOT NULL,
	"full_name" varchar(255) NOT NULL,
	"display_name" varchar(255) NOT NULL,
	"gender" varchar(20) NOT NULL,
	"birthdate" varchar(10) NOT NULL,
	"nationality" varchar(2) NOT NULL,
	"tshirt_size" varchar(10) NOT NULL,
	"source" varchar(100) NOT NULL,
	"partner_whatsapp" varchar(50),
	"partner_name" varchar(255),
	"player_level" varchar(50) NOT NULL,
	"partner_level" varchar(50),
	"tennis_squash_background" text,
	"tournaments" jsonb,
	"community_tournaments" jsonb,
	"rankings" jsonb,
	"category" varchar(20) NOT NULL,
	"playtime_constraint" varchar(50) NOT NULL,
	"terms_accepted" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "registrations_email_unique" UNIQUE("email")
);
